name: Qodana with Coverage

on:
  pull_request:
    branches: [ main, master ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Run tests with coverage
        run: mvn clean test
      
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --coverage-report=target/site/jacoco/jacoco.xml
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}